# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20161208_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
