# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_song_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_file',
        ),
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
